import { Task } from "../../dist/types/PublicTypes";

export function initTasks() {
  const tasks: any[] = [
    {
      start: new Date("2021-12-15"),
      end: new Date("2021-12-16"),
      name: "sadfsadfsadfasdfasf",
      id: "ProjectSample",
      progress: 50,
      type: "project",
      hideChildren: false,
      level: 0,
      isDisabled: true,
    },
    {
      start: new Date("2021-12-18"),
      end: new Date("2021-12-19"),
      name: "Idea",
      id: "Task 0",
      progress: 155,
      type: "task",
      project: "ProjectSample",
      level: 1,
    },
    {
      start: new Date("2021-12-25"),
      end: new Date("2021-12-26"),
      name: "Research",
      id: "ProjectSample1",
      progress: -10,
      type: "project",
      hideChildren: false,
      level: 0,
    },
    {
      start: new Date("2021-11-15"),
      end: new Date("2021-11-16"),
      name: "ProjectSample1-1",
      id: "ProjectSample1-1",
      progress: 58,
      type: "project",
      project: "ProjectSample1",
      hideChildren: false,
      level: 1,
    },
    {
      start: new Date("2021-10-15"),
      end: new Date("2021-10-16"),
      name: "Task 31",
      id: "Task 31",
      progress: 155,
      type: "task",
      project: "ProjectSample1-1",
      level: 2,
    },
    {
      start: new Date("2021-12-15"),
      end: new Date("2021-12-16"),
      name: "Task 32",
      id: "Task 32",
      progress: 100,
      type: "task",
      project: "ProjectSample1-1",
      level: 2,
    },
    {
      start: new Date("2021-12-15"),
      end: new Date("2021-12-16"),
      name: "ProjectSample1-2",
      id: "ProjectSample1-2",
      progress: 100,
      type: "project",
      project: "ProjectSample1",
      hideChildren: false,
      level: 1,
    },
    // {
    //   start: new Date("2021-12-15"),
    //   end: new Date("2021-12-16"),
    //   name: "Task 33",
    //   id: "Task 33",
    //   progress: 100,
    //   type: "task",
    //   project: "ProjectSample1-2",
    //   level: 2,
    // },
    // {
    //   start: new Date("2021-12-15"),
    //   end: new Date("2021-12-16"),
    //   name: "aaaa",
    //   id: "Task 3",
    //   progress: 155,
    //   type: "task",
    //   project: "ProjectSample",
    // },
    // {
    //   start: new Date("2021-12-15"),
    //   end: new Date("2021-12-16"),
    //   name: "aaaa",
    //   id: "Task 4",
    //   progress: 155,
    //   type: "task",
    //   project: "ProjectSample",
    // },
    // {
    //   start: new Date("2021-12-15"),
    //   end: new Date("2021-12-16"),
    //   name: "aaaa",
    //   id: "Task 5",
    //   progress: 155,
    //   type: "task",
    //   project: "ProjectSample",
    // },
    // {
    //   start: new Date("2021-12-15"),
    //   end: new Date("2021-12-16"),
    //   name: "aaaa",
    //   id: "Task 6",
    //   progress: 155,
    //   type: "task",
    //   project: "ProjectSample",
    // },
    // {
    //   start: new Date("2021-12-15"),
    //   end: new Date("2021-12-16"),
    //   name: "aaaa",
    //   id: "Task 7",
    //   progress: 155,
    //   type: "task",
    //   project: "ProjectSample",
    // },
    // {
    //   start: new Date("2020-05-01"),
    //   end: new Date("2020-05-02"),
    //   name: "aaaa",
    //   id: "Task 8",
    //   progress: 155,
    //   type: "task",
    //   project: "ProjectSample",
    // },
    // {
    //   start: new Date("2020-05-01"),
    //   end: new Date("2020-05-02"),
    //   name: "aaaa",
    //   id: "Task 9",
    //   progress: 155,
    //   type: "task",
    //   project: "ProjectSample",
    // },
    // {
    //   start: new Date("2020-05-01"),
    //   end: new Date("2020-05-02"),
    //   name: "aaaa",
    //   id: "Task 10",
    //   progress: 155,
    //   type: "task",
    //   project: "ProjectSample",
    // },
    // {
    //   start: new Date("2020-05-01"),
    //   end: new Date("2020-05-02"),
    //   name: "aaaa",
    //   id: "Task 11",
    //   progress: 155,
    //   type: "task",
    //   project: "ProjectSample",
    // },
    // {
    //   start: new Date("2020-05-01"),
    //   end: new Date("2020-05-02"),
    //   name: "aaaa",
    //   id: "Task 12",
    //   progress: 155,
    //   type: "task",
    //   project: "ProjectSample",
    // },
    // {
    //   start: new Date("2020-05-01"),
    //   end: new Date("2020-05-02"),
    //   name: "aaaa",
    //   id: "Task 13",
    //   progress: 155,
    //   type: "task",
    //   project: "ProjectSample",
    // },
    // {
    //   start: new Date("2020-05-01"),
    //   end: new Date("2020-05-02"),
    //   name: "aaaa",
    //   id: "Task 14",
    //   progress: 155,
    //   type: "task",
    //   project: "ProjectSample",
    // },
    // {
    //   start: new Date("2020-05-01"),
    //   end: new Date("2020-05-02"),
    //   name: "aaaa",
    //   id: "Task 15",
    //   progress: 155,
    //   type: "task",
    //   project: "ProjectSample",
    // },
    // {
    //   start: new Date("2020-05-01"),
    //   end: new Date("2020-05-02"),
    //   name: "aaaa",
    //   id: "Task 16",
    //   progress: 155,
    //   type: "task",
    //   project: "ProjectSample",
    // },
    // {
    //   start: new Date("2020-05-01"),
    //   end: new Date("2020-05-02"),
    //   name: "aaaa",
    //   id: "Task 17",
    //   progress: 155,
    //   type: "task",
    //   project: "ProjectSample",
    // },
    // {
    //   start: new Date("2020-05-01"),
    //   end: new Date("2020-05-02"),
    //   name: "aaaa",
    //   id: "Task 18",
    //   progress: 155,
    //   type: "task",
    //   project: "ProjectSample",
    // },
    // {
    //   start: new Date("2020-05-01"),
    //   end: new Date("2020-05-02"),
    //   name: "aaaa",
    //   id: "Task 19",
    //   progress: 155,
    //   type: "task",
    //   project: "ProjectSample",
    // },
    // {
    //   start: new Date("2020-05-01"),
    //   end: new Date("2020-05-02"),
    //   name: "aaaa",
    //   id: "Task 20",
    //   progress: 155,
    //   type: "task",
    //   project: "ProjectSample",
    // },
    // {
    //   start: new Date("2020-05-01"),
    //   end: new Date("2020-05-02"),
    //   name: "aaaa",
    //   id: "Task 21",
    //   progress: 155,
    //   type: "task",
    //   project: "ProjectSample",
    // },
  ];
  return tasks;
}

export function getStartEndDateForProject(tasks: Task[], projectId: string) {
  const projectTasks = tasks.filter(t => t.project === projectId);
  let start = projectTasks[0].start;
  let end = projectTasks[0].end;

  for (let i = 0; i < projectTasks.length; i++) {
    const task = projectTasks[i];
    if (start.getTime() > task.start.getTime()) {
      start = task.start;
    }
    if (end.getTime() < task.end.getTime()) {
      end = task.end;
    }
  }
  return [start, end];
}
